### ISSUE TITLE
Håndtere at bildefilen til overlay ikke finnes i mange tilfeller

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/data.artsdatabanken.no#3]
Vi genererer en url, men har ingen sjekk for om bildet eksisterer før det forsøkes å tegne den opp, som gir oss et broken image-ikon der den ikke finnes. 
Burde hatt en eller annen sjekk før den prøver å bygge?

Usikker på hvordan å fikse.

**Comment by bjornreppen** [comment]
![image](https://user-images.githubusercontent.com/281359/54748110-0673a100-4bd1-11e9-9035-7357d99ebbe4.png)

Foreslår at vi mater inn den kunnskapen i json-fila.  Har en mistanke om at den i dag bare antar at det finnes en fil uten å sjekke. Jobben som lager fila leser allerede indeks over bildefilene https://data.artsdatabanken.no/index.json så her bør det være relativt lett å bare lage noden bare hvis det finnes bilde.

**Comment by helemork** [comment]
Forøvrig pratet jeg nettopp med de som jobber med nettsideversjonen til nin, og de sier de bruker "kartet fra data.artsdatabanken.no". betyr det at de bruker komponenten direkte? 
Isåfall kan vi jo ikke ha ekstern css, siden det da ikke blir med utenfor. men det gjør det vanskelig å sikre støtte på ie og safari. isåfall må vi forenkle litt hvordan den fungerer. @bjornreppen

**Comment by bjornreppen** [comment]
Mulig de har snagget svgen? :-)  Jeg er ikke kjent med hva de har gjort.  Jeg tror den løsningen du har lagt opp til nå med 2 bilder stacket oppå hverandre uten tvil er en mye bedre løsning også for dem.

**Comment by helemork** [comment]
hvem skal jeg kontakte for å informere om hva som trengs for å få det riktig?

**Comment by bjornreppen** [comment]
Torstein

**Comment by bjornreppen** [comment]
Ok.. her så jeg ikke hele utfordringen.. jeg tenkte bare på fotoet.. men dette gjelder selvfølgelig også kartet.   Prøver å gjøre tilsvarende der.

**Comment by bjornreppen** [comment]
JSON-fila inneholder nå pekere hvis det finnes bilder
