### ISSUE TITLE
[Innhold] - Bedre overskrift. Endre til "Åpne Data". Oppdater Alle steder det brukes

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/data.artsdatabanken.no#4]
- [ ] Endre i alle lenker
- [ ] Endre i overskrifter
- [ ] Endre i referanser

**Comment by bjornreppen** [comment]
Synes det er kort og godt navn.  Selv om vi også har APIer der så handler vel også APIene om å få tak i åpne data litt om gangen istedet for alt på en gang.

**Comment by runningbones** [comment]
Enig
